# Generated by Django 3.2.25 on 2025-07-18 05:15

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bakery_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Items', models.CharField(default='Enter.....', max_length=45)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(10000)])),
                ('Date', models.DateTimeField(default=datetime.datetime.now)),
                ('Image', models.ImageField(upload_to='image/')),
                ('Link', models.URLField(default=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='register_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=45, unique=True)),
                ('Email', models.EmailField(max_length=60, unique=True)),
                ('Password', models.CharField(max_length=180)),
            ],
        ),
    ]
