# Generated by Django 3.2.25 on 2025-07-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakery_models',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
