# Generated by Django 3.2.25 on 2026-05-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0007_auto_20260510_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakery_models',
            name='Category',
            field=models.CharField(choices=[('Cakes', 'Cakes'), ('Pastries', 'Pastries'), ('Breads', 'Breads'), ('Cookies', 'Cookies'), ('Muffins', 'Muffins'), ('Pizza', 'Pizza'), ('Shakes', 'Shakes')], default='select', max_length=30),
        ),
    ]
