# Generated by Django 3.2.25 on 2026-05-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0009_remove_bakery_models_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_model',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
