# Generated by Django 3.2.25 on 2025-07-18 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_bakery_models_stock_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bakery_models',
            name='stock_quantity',
        ),
    ]
