# Generated by Django 3.2.25 on 2026-05-09 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0003_remove_bakery_models_stock_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bakery_models',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='bakery_models',
            name='Link',
        ),
        migrations.AddField(
            model_name='bakery_models',
            name='Stock',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Preparing', 'Preparing'), ('Delivered', 'Delivered')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.register_model')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.bakery_models')),
            ],
        ),
    ]
