# Generated by Django 3.2.25 on 2026-05-11 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0008_bakery_models_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bakery_models',
            name='Category',
        ),
    ]
