# Generated by Django 3.2.25 on 2026-05-11 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0010_register_model_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_model',
            name='is_admin',
        ),
    ]
