# Generated by Django 3.2.25 on 2026-05-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0011_remove_register_model_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_model',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
